### ISSUE TITLE
Create Selection from Layer: Process hibernated

### ISSUE THREAD

**Issue by Gjanosh61** [erpas/serval#45]
Hello,
When working on a DEM with many water bodies I use the "Create Selection from Layer" function which works very well on small polygons selected on a .shp. Sometimes I have to deal with large polygons of water and consequently the pixels of the DEM within the selection are a large number. When I start the process...Serval goes into hibernation...and I don't understand if it crashed or needs much more time to complete the operation.
By any chance, is there a limit to the size of the polygon (pixels inside)? If yes ... it is possible to have a visual reference of the time left until the operation is completed.

Regards

![Immagine 2023-09-12 200512](https://github.com/lutraconsulting/serval/assets/22433856/7605a993-cc2a-4b51-979c-dc4f6eecbb18)
![Immagine 2023-09-12 202458](https://github.com/lutraconsulting/serval/assets/22433856/2f523365-b7bc-4aea-bb76-45d3b55baf5c)
![Immagine 2023-09-12 202529](https://github.com/lutraconsulting/serval/assets/22433856/11862be0-ee95-4346-8c90-86bf8bf6bd9f)

**Comment by erpas** [comment]
There is no hard limit - it would depend on your individual resources.

As stated in the docs, Serval is intended to be used on small portions of a raster. If you need to process huge amount of raster cells, I would suggest raster calculator.

Also, your project CRS is EPSG:4326 - you really need to use a projected CRS instead of lat/lon.
